---
- name: Login in OpenShift as administrator
  shell: "oc login --insecure-skip-tls-verify=true -u {{ admin_username }} -p {{ admin_password }} {{ openshift }}"

- name: Give Jenkins Service Account admin privileges
  shell: "oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:ci:jenkins -n ci"

- name: Login in OpenShift as regular user
  shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"

- name: Create a new CI OpenShift project
  shell: "oc new-project ci"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"

- name: Create an OpenShift pipeline in CI project
  shell: "oc create -f https://raw.githubusercontent.com/ravichalla/aloha/master/pipeline.yml"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
